In [35]:
import pandas as pd 
import numpy as np

In [73]:
t = pd.read_csv('tourism.culture.csv', index_col=0)
t

,CountryNumber,Data,Cont.,Series,1995,1996,1997,1998,1999,2000,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Notes
0,4.0,AFGHANISTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Inbound tourism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Arrivals - Thousands,NaN,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,NaN
3,NaN,Tourism expenditure in the country - US$ Mn,NaN,IMF,..,..,..,..,..,..,...,147,165,167,179,121,86,62,16,50,NaN
4,NaN,Travel - US$ Mn,NaN,IMF,..,..,..,..,..,..,...,75,85,102,138,109,79,49,2,28,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487,NaN,Departures - Thousands,NaN,TF,256,69,123,213,331,..,...,650,693,720,2946,3182,3393,3192,2768,2987,NaN
2488,NaN,Tourism expenditure in other countries - US$ Mn,1/,IMF,106,118,120,131,..,..,...,203,317,387,441,451,557,406,338,..,NaN
2489,NaN,Travel - US$ Mn,NaN,IMF,..,..,..,..,..,..,...,131,228,272,337,342,476,327,315,..,NaN
2490,NaN,Passenger transport - US$ Mn,NaN,IMF,..,..,..,..,..,..,...,72,89,115,104,109,81,79,23,..,NaN
2491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
t['Data'] = t['Data'].fillna('Unk')
t['CountryNumber'] = t['CountryNumber'].fillna('Unk')
t_2 = t[(t['Data'].str.contains('expenditure')) |
        (t['CountryNumber'] != 'Unk')].reset_index(drop=True)
t_2.drop(['Cont.', 'Series', 'Notes', 'CountryNumber'], axis=1, inplace=True)
t_2.replace('..', np.nan, inplace=True)

t_2.fillna(0, inplace=True)
t_2['total'] = t_2[1:].sum(axis=0)
t_2

,Data,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,total
0,AFGHANISTAN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,Tourism expenditure in the country - US$ Mn,0,0,0,0,0,0,0,0,0,...,147,165,167,179,121,86,62,16,50,NaN
2,Tourism expenditure in other countries - US$ Mn,0,0,0,0,0,0,0,0,0,...,106,255,110,138,140,151,89,130,226,NaN
3,ALBANIA,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
4,Tourism expenditure in the country - US$ Mn,70,94,34,60,218,398,451,492,537,...,1778,1833,1623,1670,1849,1613,1821,2050,2306,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,Tourism expenditure in the country - US$ Mn,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
659,Tourism expenditure in other countries - US$ Mn,0,0,83,81,100,102,102,109,115,...,167,223,303,357,378,400,423,410,478,NaN
660,ZIMBABWE,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
661,Tourism expenditure in the country - US$ Mn,145,232,205,158,202,125,81,76,61,...,135,164,174,183,186,191,194,158,0,NaN
662,Tourism expenditure in other countries - US$ Mn,106,118,120,131,0,0,0,0,0,...,203,317,387,441,451,557,406,338,0,NaN

In [101]:
with open('list1.txt') as l:
    list1 = l.readlines()
    list1 = [x.strip('\n') for x in list1]
    list1 = list(map(int, list1))
    
with open('list2.txt') as l:
    list2 = l.readlines()
    list2 = [x.strip('\n') for x in list2]
    list2 = list(map(int, list2))

print(len(list1), len(list2))

200 200

In [102]:
list1.extend(list2)

In [107]:
final = sorted(list1)
len(final)

400

final[99]

That is, given P1 = (x1,y1,z1) and P2 = (x2,y2,z2), the distance between P1 and P2 is given by d(P1,P2) = (x2 x1)2 + (y2 y1)2 + (z2 z1)2.

In [148]:
with open('coords.txt') as c:
    coords = c.readlines()
    coords = [c.strip('\n') for c in coords]
    coords = [c.split(' ') for c in coords]
    coords = [{c[0][:-1] : (float(c[1][:-1]), float(c[2][:-1]), float(c[3][:-1]))} for c in coords]

max_distance = 0
keys = []
for i in coords:
    for j in coords:
        for key1, value1 in i.items():
            for key2, value2 in j.items():
                temp_distance = (
                    (value2[0] - value1[0])**2 + (value2[1] - value1[1])**2 + (value2[2] - value1[2])**2)**(1/2)
                if temp_distance > max_distance:
                    max_distance = temp_distance
                    keys = [key1, key2]
max_distance
keys

['B', 'X']

In [154]:
with open('mode_nums1.txt') as m:
    lines = m.readlines()
    lines = [line.strip('\n') for line in lines]
    lines = list(map(int, lines))
    
with open('mode_nums2.txt') as m:
    lines2 = m.readlines()
    lines2 = [line.strip('\n') for line in lines2]
    lines2 = list(map(int, lines2))
    
lines.extend(lines2)

In [156]:
max(set(lines), key=lines.count)

16

In [242]:
with open('roman_numbers.txt') as rn:
    lines = rn.readlines()
    lines = [line.strip('\n') for line in lines]
    lines = list(map(int, lines))

class py_solution:
    def int_to_Roman(self, num):
        val = [
            1000, 900, 500, 400,
            100, 90, 50, 40,
            10, 9, 5, 4,
            1
            ]
        syb = [
            "M", "CM", "D", "CD",
            "C", "XC", "L", "XL",
            "X", "IX", "V", "IV",
            "I"
            ]
        roman_num = ''
        i = 0
        while  num > 0:
            for _ in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i]
            i += 1
        return roman_num


numerals = []
for val in lines:
    numerals.append(py_solution().int_to_Roman(val))
numerals

['MMCCIII',
 'MMMCCXXXI',
 'MMDCXVI',
 'MDCLI',
 'MMCMXXXVI',
 'MMMDCCCLXVII',
 'MMXVIII',
 'MMCXLVII',
 'MMCMXXVIII',
 'MCCXC',
 'MMCDXIV',
 'MCCXXXI',
 'CXLVI',
 'CMXXXVI',
 'CXXXVIII',
 'MMMDCCCXLVII',
 'MMMDXVII',
 'MDCLXXVII',
 'XLVI',
 'MMMDX',
 'MMMCMXCII',
 'MMCXIV',
 'MMMDXXXVI',
 'MDCCCXVI',
 'MMDLIII',
 'DCCCXCIII',
 'CMLIV',
 'DXXII',
 'CCV',
 'MMMDCCLXXVII',
 'MXCI',
 'MMMDXXVI',
 'MMCDLXXIX',
 'MMDCLXXII',
 'MMMCLXXIV',
 'CCCLIX',
 'CDIII',
 'MMMDCCXLVIII',
 'MMMLXXX',
 'CCI',
 'MXXXVIII',
 'DLIII',
 'MDCCCLXXVIII',
 'MMMDCLXIV',
 'CCXI',
 'MMMCXLV',
 'MMCLVIII',
 'MMCCCLIII',
 'MCDXCIX',
 'MCLXXXVIII',
 'MMCCXC',
 'MMDCCLXIV',
 'MMMDLVII',
 'CXLIX',
 'MCCCX',
 'MMDCXCV',
 'MMDCXCI',
 'MCXIII',
 'MMMCCLXXIII',
 'CDLXXXII',
 'DXXIII',
 'DCCXXXIII',
 'MMCDL',
 'MCLXXVIII',
 'MMMCCCXCI',
 'CDLXIII',
 'MMMDCXXXI',
 'MCCCXIII',
 'MDXVIII',
 'MMMDL',
 'MDCCCXX',
 'CCXLVI',
 'MDCCCXLIV',
 'MMCX',
 'MMMXCIX',
 'DCXLIV',
 'MMCCXXVIII',
 'MMDCCXIII',
 'MCDLXI',
 'CCCXXVIII',
 'CMXXXII',
 'MDXCIV',
 'XXXVIII',
 'MCCCXXIX',
 'MMCCXLII',
 'MMCDXCII',
 'DCCCXCVI',
 'MMDCCLXVII',
 'MMCMLXXI',
 'MCMXXXVI',
 'MCCLXXI',
 'CCII',
 'MMMCDXCVIII',
 'MMDCLXVIII',
 'MDLVII',
 'MCCXXIV',
 'DCCCLXX',
 'MMMDCCLIX',
 'MCCLII',
 'MCLXXXVI',
 'MDCL',
 'MMDCCCXCVII',
 'MDLXVIII',
 'MMCXXXIX',
 'MDCCCXXXV',
 'MDCCCXXV',
 'MMDLXVII',
 'CCI',
 'MMMLXXII',
 'MCDLIV',
 'MMMCXLIV',
 'MMCLXXXIV',
 'MMMCCCLIX',
 'DCV',
 'MMCXLVIII',
 'MMMCXXXV',
 'MCXLVII',
 'MDCCCLXVI',
 'MMMDXIV',
 'MMMDCCXIV',
 'CI',
 'MMMLXXXIII',
 'DLXXXVIII',
 'MMMDCXCIII',
 'DCXLVIII',
 'MMCCLXXXI',
 'MMCLXVIII',
 'MCCI',
 'CLXXXIV',
 'MMMXXVIII',
 'MCDXXI',
 'MMMDLXXX',
 'CDXV',
 'DCCXCVI',
 'MMMCCCXCIII',
 'MMCDI',
 'DCCXVIII',
 'MCCCLXV',
 'MMCXXXIX',
 'MMMCCLXXIV',
 'MMDCCXXXVIII',
 'MCCCLXXVII',
 'MDLXI',
 'MMMCCCLXXXIII',
 'DCIII',
 'CMXVI',
 'MCDLXX',
 'MMMDCLV',
 'MMMCLXX',
 'MDVII',
 'MMMDCCCLXXVII',
 'MMCDXCI',
 'MMMCCCLXXIX',
 'CMXCIX',
 'MMDLXXVI',
 'MCCCXXXIII',
 'MCLXXIV',
 'MMCD',
 'MMMLVI',
 'MMMCCLVII',
 'MCMLXXVII',
 'MMMCMLXXI',
 'XCIX',
 'MCCCXCVII',
 'MMMCLXIII',
 'MMMCMLXVII',
 'DCCCXXXIV',
 'MMCLXVII',
 'CDXCVI',
 'CLXXXII',
 'CCLVII',
 'MMDXXII',
 'MDCCXLV',
 'CCXCIII',
 'MMCDXXII',
 'MMMCMLI',
 'MCDLII',
 'MMXXIII',
 'MDCCXCIV',
 'MCMXCI',
 'MMCCXXXIII',
 'MDCCCXCVII',
 'MMMDCXCIV',
 'MMCLXXXVI',
 'MMDCXV',
 'MCDXIII',
 'MCX',
 'CCCXCVII',
 'CMLXVII',
 'MMDCCIII',
 'MMMVI',
 'CXXXI',
 'MDCCCXCI',
 'CDLXXVI',
 'MMCCLI',
 'MCLI',
 'DCLXXVI',
 'MMMLIX',
 'MMDCCLIV',
 'MMCDLXXII',
 'MMMCCXXIX',
 'MDCXXXIV',
 'DCCXV',
 'MMCLXIX',
 'MMCDV',
 'DLIX',
 'MMCXX',
 'MMDXLII',
 'MCCCLXVII',
 'MMMDXLV',
 'DCCXXVII',
 'CCXCVIII',
 'MMMDLXXXII',
 'MMCCCLXXXIX',
 'XLVI',
 'MMDCCCXLIV',
 'DCCCLXXXIV',
 'MMDCLIX',
 'DXCIII',
 'MMMDCLXXI',
 'MMCCCXXIII',
 'MMCXXX',
 'MMMDXLII',
 'DCCCXXIX',
 'MMMDCLII',
 'MMMDCXXII',
 'DCCLI',
 'MMCDXIV',
 'MMMCX',
 'MMCCLIX',
 'MMCDLXVI',
 'MCDLXXIX',
 'DXVI',
 'MCLV',
 'MMMDCLXXXVII',
 'MMCCCXXV',
 'MMMCCXIX',
 'MMMCXI',
 'MDCCCLXXXIX',
 'MIV',
 'MCDXCIX',
 'MDXIX',
 'LXXIV',
 'LIV',
 'CXLI',
 'MDCCCXXXIX',
 'XCVIII',
 'CXIV',
 'XVI',
 'DCXV',
 'MMDCLXXV',
 'DCCXXXVII',
 'MMLXVIII',
 'MMCCCLXVIII',
 'CMXXXIII',
 'MMCXXXI',
 'MMMCCCV',
 'MDCCCIII',
 'MMMDCLVII',
 'CCXCVIII',
 'MCMXLIX',
 'MMXLV',
 'MMXXI',
 'MCCCLXIV',
 'MMDCCIII',
 'CMXXX',
 'MMCXLV',
 'DCCXVIII',
 'MMMCMLXV',
 'MMMCCCLXV',
 'MLXV',
 'DLXXXVI',
 'CDXCVII',
 'CXVI',
 'MMMCX',
 'MCCXXXVII',
 'MCCCXLVII',
 'DCCCXLVIII',
 'DXXXIV',
 'MDCCXXII',
 'CCCXXVII',
 'MLI',
 'MCDXLVII',
 'MMCCCXXXIII',
 'MXXVII',
 'MMCCLII',
 'MDCCXXIX',
 'CII',
 'MMMDCCLXXVIII',
 'MLXXXVII',
 'MMMCXIV',
 'DCLII',
 'MCXII',
 'MDCXX',
 'MCXLIX',
 'MCCXVI',
 'MMMDCCCLXXXIII',
 'CCV',
 'MMCXCII',
 'MMMCCCXXIV',
 'MMMCMLV',
 'MMCDLXXXIII',
 'MMMDCCCLII',
 'CCCXVI',
 'MMDCLXXVII',
 'CCCLIII',
 'MMMDCCXXV',
 'MMMDCCLXXXIII',
 'CMLXXXVIII',
 'MMCDLXXIV',
 'CML',
 'DCCCIV',
 'MMMDCCLXXV',
 'CMLXXXI',
 'CXXII',
 'MCCCXXV',
 'MMMCCCXCIV',
 'MMCCCLV',
 'DCCXLVI',
 'CDLIII',
 'MDCCCLXXII',
 'MMDCCXXXVI',
 'CMLXXXVI',
 'DCXLII',
 'MCMLVI',
 'MMMCCCLVII',
 'MDXXXVI',
 'MCDXL',
 'CCLXIX',
 'MMCCCLXX',
 'MMCCCIII',
 'MDLXI',
 'DXLI',
 'MMDCCXXVII',
 'CDXXVI',
 'MCLXXX',
 'CCCXXXII',
 'MDCCXIII',
 'MMCXIX',
 'MMMCMXXXIV',
 'CDXLV',
 'MMMCCLXXXV',
 'MMCCCXXIX',
 'MCXCI',
 'MCMLIV',
 'MDCCCX',
 'MMDCCLXXIX',
 'MCDXXV',
 'MMMCCCLXVII',
 'MCXXXVII',
 'VIII',
 'CXLII',
 'MMMDXV',
 'MMCMXVII',
 'MMMCCCLXXIV',
 'MMCMXIV',
 'MMMDCCXVI',
 'CCXVI',
 'CXX',
 'DCXLVIII',
 'MCCCXXVIII',
 'MMMCDLXIV',
 'MMMDCLXXVII',
 'MMMCMXLVIII',
 'MMCMLXXXV',
 'MMCCXXXII',
 'CLXVII',
 'DXXXV',
 'MMXLIX',
 'MDCIII',
 'MMLXXXIII',
 'MDCCXLII',
 'MMCLXXXII',
 'MDCCXLIII',
 'DLIX',
 'MLX',
 'MMCXLVII',
 'MDCCV',
 'DCCXXXIX',
 'MMMDX',
 'DLIII',
 'MMDCXX',
 'CCCXXIV',
 'CCCLXVII',
 'CDLXXII',
 'DCXXXVI',
 'MMDCLV',
 'MDXI',
 'DCCXLVI',
 'MCMXVI',
 'MMCCCLXXII',
 'MMMDCCLXIII',
 'MMMCCCLXXXIII',
 'MMMCCLXXXVI',
 'MMDCCI',
 'MMMCIX',
 'MMDCCLXXXVII',
 'CDLXXIII',
 'MMMCXCIII',
 'MMMCXLVIII',
 'CLV',
 'MDCCLXXXVIII',
 'MCCCXXIX',
 'MDCCLV',
 'MDCXXXI',
 'MMMCMLXXXVIII',
 'MMMCDXLI',
 'MCCLXXX',
 'MMMCLV',
 'MMCDLXXXII',
 'DLXXIII',
 'MCCXCV',
 'MCMXXXVIII',
 'MMCCCIV',
 'MMDXLII',
 'DCCXC',
 'MMDCCCLXXIII',
 'MMLXVIII',
 'MMCCLXXXIV',
 'MMMDCIX',
 'MMCXXII',
 'MMLIII',
 'DCCCXXIX',
 'MMDCXX',
 'MMDCCLXXVIII',
 'MMDLXXXVII',
 'MCCL',
 'CCXXXVIII',
 'DCCCXXXIII',
 'CCVIII',
 'CMLXXIII',
 'MMMCVI',
 'MMMDCCCLXIX',
 'CCCXCVI',
 'MMCMXLI',
 'MMDCVIII',
 'MCDLXVI',
 'MMDXXX',
 'MCCXXIX',
 'MMCCXLVI',
 'DXVII',
 'MCCCLXXXV',
 'MMMDCCLXIII',
 'MCCCXI',
 'MMCXCI',
 'MMDIV',
 'DCXII',
 'MMMDCCCIV',
 'MCMVIII',
 'DCCXL',
 'MCDX',
 'MCDLXI',
 'MCLXXIX',
 'MMDCCCLXVIII',
 'MMCMXC',
 'MCCXXXI',
 'MCDXXVIII',
 'MMMDLXXXIII',
 'CXXI',
 'CDLXXVIII',
 'MMDX',
 'MCCCVII',
 'DCCCXXII',
 'CCCIV',
 'MMDIII',
 'CLXIII',
 'MMMCMXVI',
 'MMVI',
 'MCXLVII',
 'MDCCXCVI',
 'MMCDXIV',
 'CMXXXVIII',
 'CLXXII',
 'CCCV',
 'MCDLXXXVIII',
 'MMMLXV',
 'MMMCLXX',
 'MMMDCCCXXXIX',
 'MMDCCLXXXVI',
 'MMDCCLXII',
 'DXLIII',
 'MCDXXIII',
 'MMMDCXXII',
 'CMXLVIII',
 'MCXXXVIII',
 'LXIII',
 'MMMCDV',
 'MMMCCVII',
 'CDLXI',
 'DCCCXL',
 'CXXV',
 'MMMDCI',
 'MMCLXXXVII',
 'MMDCCCLIV',
 'MMMCMXXIV',
 'CCLXXI',
 'DVIII',
 'MMDLXXVIII',
 'MDCCCXIII',
 'MMMXLIX',
 'MMMCCLXXXIV',
 'MDXXIII',
 'CDXLIV',
 'MMXLIII',
 'MMMXVIII',
 'MCCCXXXVII',
 'MCLIV',
 'CXCI',
 'MCDXXXII',
 'MCMLXXXII',
 'CCCXXII',
 'MMDLXXXIII',
 'MCCCLXXXIV',
 'MDCXI',
 'MMDCCLVII',
 'MCCIX',
 'DCXLI',
 'MDCCCLXXV',
 'MMDLVII',
 'MCDXCIII',
 'MMMDCCXCVII',
 'MMMDCX',
 'MMMLVIII',
 'MMMCDLIII',
 'DXXXII',
 'DXXXIV',
 'CCCXLV',
 'MMMDLXIII',
 'MMMCCCXCVI',
 'MDCLXXXIV',
 'MCMXCVIII',
 'MMMLXIII',
 'MDCLXVI',
 'MMMCLV',
 'MMMCMXXXIV',
 'MMMCLXXI',
 'MDCIII',
 'MMMCDXI',
 'CCLXVIII',
 'CCCLXIV',
 'MMDCLXXI',
 'XXXIX',
 'MMDCCCLX',
 'CCCLI',
 'MDLXII',
 'MX',
 'MMCCXLVII',
 'MMDCXLV',
 'MDXXX',
 'MMMIV',
 'MMMCDLXXVII',
 'MMCLXVII',
 'MCCCIII',
 'CMXCVII',
 'DCCIV',
 'MXLVI',
 'MCDLXXVIII',
 'MMMDLXIII',
 'MMMDLXXXIX',
 'CCCLXXVI',
 'MMDCXXXIII',
 'MMMCCCIII',
 'MMMDXXXV',
 'DCCXXXIII',
 'MMMCDLXVII',
 'MMCMLXXXVII',
 'MMCDXII',
 'MDCCXXXIII',
 'CCCXLII',
 'MMMCMXCIX',
 'MDCVII',
 'MMCDLV',
 'XLVII',
 'MMMCDLXVI',
 'MMXCV',
 'DCCXV',
 'MMII',
 'MMMLXXXVIII',
 'CDLXXVIII',
 'MCCCXCVI',
 'MMMCMLXXIX',
 'MMCCCLXIII',
 'MMDCLVII',
 'MMMCDLXXIV',
 'MDLXI',
 'MMCCCI',
 'DCCCXCVII',
 'DCCCLVII',
 'MDCCCLXIX',
 'MXXXI',
 'MDCLXVIII',
 'XXXV',
 'MDCCLX',
 'CCLXXXIV',
 'CMXXXII',
 'MMMDLXIII',
 'MDCLXXII',
 'CXLIV',
 'MMMCMLXXVI',
 'CCLXXI',
 'MCMLIV',
 'MMCCCLII',
 'MMDCCXC',
 'MMMCMLI',
 'MMCCCXXXI',
 'MMMXLII',
 'MMCLXIX',
 'MDCLXXIII',
 'MMCCCXCIV',
 'MMDXXIX',
 'MMCCCLII',
 'XC',
 'MMMDCCLXXVII',
 'MCMXII',
 'MMCLX',
 'MMMDCCXXII',
 'MMMLXXIX',
 'MCDLXXXVII',
 'MMDXCI',
 'MMMCCCLXXXIII',
 'MMMXCVIII',
 'MMDCIV',
 'MCCCXCIX',
 'MDLXXXVII',
 'MMMCDXXIII',
 'MMMCDXII',
 'MDCLIX',
 'MMCDXXXIX',
 'MMMCDXXXIII',
 'CCCLXXIX',
 'DCCCXXI',
 'MMCMLXXXI',
 'MMDCCCLXXI',
 'MMCCLXXV',
 'MCDXXXV',
 'DCCXCVI',
 'MMMCDXV',
 'DCCCXCIX',
 'MCLXXXVI',
 'DCCCXXXII',
 'MMDCCXCV',
 'MMMDLXXXIX',
 'MMCXXXV',
 'MMMCIV',
 'MCCCII',
 'MXXXVI',
 'DCXIX',
 'DCXLIX',
 'MMCCCLXXVIII',
 'MMCMIII',
 'MDCCVI',
 'CMXXVI',
 'MMDCCLXXXVII',
 'CCCLVI',
 'MCDLIII',
 'MMCMXXXIX',
 'MMMCCXIII',
 'MCMXXIX',
 'MMDCCXCI',
 'MMMCCCXLVIII',
 'MMMDLXII',
 'MCMLXVII',
 'CMXXXVI',
 'MMCCCXXXIX',
 'MMMCLXXXVIII',
 'MDCCXLII',
 'DLXXV',
 'MMMCDXV',
 'MDCCCLXI',
 'MMDCXXXVI',
 'MMMLXXI',
 'DCCXII',
 'MCC',
 'XCIV',
 'MMMDV',
 'MMCDXXXVIII',
 'MMCMXCIX',
 'MCCXXII',
 'MMCMXVI',
 'MCMXLVII',
 'MMMCCCLXX',
 'MMDCCCXVIII',
 'MDCCCXXX',
 'MCDLXXI',
 'DCCLI',
 'MCDXCIII',
 'MCXLV',
 'MMMDCCCLV',
 'MMCLXXIV',
 'MCCXCI',
 'DVII',
 'MDCCXLIII',
 'DCCCXXXIX',
 'MXCII',
 'MCCXXVIII',
 'MDCCXXX',
 'MDCCLXXXII',
 'MDCCCXIII',
 'MMMDLI',
 'MMMLV',
 'MMCDVIII',
 'MIII',
 'MMMCDLXIX',
 'MMMCDXLIII',
 'CLXXVIII',
 'DCCLXXXI',
 'CCXXXIX',
 'DCCCV',
 'MMMCCCXXVI',
 'MMCDXXVII',
 'MMMDCCCXCV',
 'MMMDCXVI',
 'MMXLV',
 'MMDCXV',
 'MMMDCCI',
 'DCCCLXV',
 'MDCCCLXXXVI',
 'DCCXCII',
 'MMMDCCCXCVII',
 'MMMCCCLII',
 'DCCXXI',
 'MMCLXXVII',
 'DCCLX',
 'MMDCLXV',
 'MMCDLV',
 'CLXVII',
 'MMDXXIX',
 'MMCDLIV',
 'MCCXCVI',
 'MMMDXXXIII',
 'MMCMXLV',
 'MCCXXVI',
 'MMCXLII',
 'MMMDXXV',
 'CXCIII',
 'DLXXV',
 'CCCXCII',
 'MMMDCCLVIII',
 'MCCCLXXXVII',
 'CDLXXX',
 'MMCMXXXIX',
 'MDCLVI',
 'MCDXXX',
 'MMMDXCIII',
 'MCMXLVI',
 'DCXV',
 'DXXX',
 'MDXCVIII',
 'CDXXXI',
 'MMMDXIX',
 'CCCLV',
 'CCV',
 'CCCXX',
 'MMMDCXLVI',
 'MXCV',
 'DCCLXXXIV',
 'MCDXXXV',
 'MCMLXXI',
 'MMMCDXCIV',
 'MDXXXIV',
 'CMLXIX',
 'MMCLIV',
 'MMCCLXXXVII',
 'MMMCMXCIII',
 'CCCXCVIII',
 'MLXIII',
 'MDXXIX',
 'CMLII',
 'MMMDCCCXLII',
 'DCCCXCIV',
 'MDCCCX',
 'MCCXC',
 'MMMDCCLXVII',
 'MMIV',
 'MCCCXLI',
 'CCXXXIX',
 'MDCCLXVIII',
 'MMCCLXXXIII',
 'MMMDXCVI',
 'DCCXXII',
 'MMMDCXXXVII',
 'MDCCCLXVII',
 'MMCCCL',
 'MMMCDLXXVI',
 'MCCXI',
 'CDLXIII',
 'MDCCCLXVI',
 'MDCL',
 'MMDCCLXXXVIII',
 'MDCCCXCI',
 'MCCCXXIX',
 'MDCCXLVI',
 'MMCCLIV',
 'MCDLXXXVII',
 'CCXXXIV',
 'MCCVIII',
 'MMMLXXIV',
 'MMMDCCVIII',
 'MDCCCXXXIX',
 'MMMCCLXXI',
 'CMXXXV',
 'DCCCLIX',
 'MMMLXXIII',
 'MMMDCCCX',
 'MMMDCCX',
 'CMLXVII',
 'MDCXXIX',
 'DCI',
 'CCCXLIII',
 'CLXVI',
 'MMCMXXVII',
 'CCCLXXXI',
 'CL',
 'MCMV',
 'MMCCCXVI',
 'DLXXVII',
 'MMCLXXIV',
 'MMMCDXI',
 'MMMCLV',
 'DCCII',
 'MMDCVII',
 'MMMCCCXIII',
 'MMCDLXI',
 'MMMDXXV',
 'XLVI',
 'MMMCMLXVI',
 'MMLXXIII',
 'MMMDI',
 'MMDCXCV',
 'DCCCXCIV',
 'MMMXCIV',
 'MMDCCL',
 'MLXX',
 'MMMDCXCVIII',
 'CM',
 'MMDCLXIII',
 'MMCXLVIII',
 'XXIV',
 'MCCLXXXIV',
 'VIII',
 'MCD',
 'MDXXIV',
 'MMCCLXXI',
 'MXXXII',
 'MCIV',
 'DCCCLXI',
 'MMCI',
 'MMMCMVII',
 'MCXXI',
 'MMDXVII',
 'MDCCCXVI',
 'MMDXCVIII',
 'MMMCCIV',
 'MMCMLVI',
 'CMXXXVII',
 'MMMDCLXX',
 'MMMDCCXVI',
 'MCXXIV',
 'MMMDCCXXXII',
 'MMCMLII',
 'MMCMXLVIII',
 'MDLXXII',
 'MMCDLIII',
 'MCCLXXXII',
 'CCCXLVI',
 'MMCCLXXXVIII',
 'CDXCVI',
 'DCCXXXII',
 'MMMCLXXV',
 'MMDCCLVI',
 'MMDCCCLXXIX',
 'MMMDCXXXVIII',
 'MDCXIV',
 'MMMCCLXIV',
 'MLXX',
 'MCXXII',
 'MMMCDLXII',
 'DCXCVIII',
 'MMCMLXXXVI',
 'MMMDXCVIII',
 'MMCMLVI',
 'MMMCMXXXVI',
 'MDCLXXXIX',
 'MMMXL',
 'CCXLII',
 'MCCCXIX',
 'MCCLXXXVIII',
 'MMCLXV',
 'MMCCLXXI',
 'MMMCDIX',
 'MCMLXI',
 'MMDCII',
 'MMDLIV',
 'MMDCXCIV',
 'CDXIII',
 'MMMDCCXLVI',
 'DCCCXLIV',
 'MMMDCCCLXXXVIII',
 'MDCCXL',
 'MMMCCCXLII',
 'MMMDCCCX',
 'MMMCXXXI',
 'MMMCCLVII',
 'MMMLXXXVIII',
 'MMMCDLXVIII',
 'CMLXXXVIII',
 'DXCIII',
 'MMMCCLI',
 'MMMCDXCIX',
 'MCDXCVI',
 'CDLXV',
 'MMCCXCV',
 'MDCXXXIX',
 'MMDII',
 'MCMXXV',
 'MMMDCXCVII',
 'DXLIII',
 'MMMCCCXXXIII',
 'DCCCXXXV',
 'MMCMLIX',
 'MCMXIX',
 'VIII',
 'MLXXXIX',
 'MMMDCCCXXXIII',
 'DLVIII',
 'DXX',
 'MCCVII',
 'MMDCCCLXXIX',
 'MMDCLXXXIII',
 'MMMDIX',
 'MMDLXIII',
 'MCDXCIX',
 'MMXXXVI',
 'MMMCMLXIV',
 'MMCCCXIV',
 'CMLXXXVI',
 'MMCCCXX',
 'MDV',
 'MMMDCXLV',
 'MMMDXX',
 'MMMCLXVI',
 'MMMDCCXXXIX',
 'DCCCLIV',
 'MMCLVI',
 'DCCXCI',
 'MMDLXXXVII',
 'MMMCCCLXXX',
 'MCCLXVI',
 'MMMCCLXXIX',
 'MMDCCLXXI',
 'CCCLXXIII',
 'MMMDCCLXXXVI',
 'MXL',
 'MMCCLVI',
 'MCMXIX',
 'MMMCDXLI',
 'MDLXII',
 'MCI',
 'MMCCCI',
 'MMMDCCCLXXXVIII',
 'MMMCCCVI',
 'MXCVIII',
 'MMDCCXX',
 'MMCCCXXXIX',
 'MMCDLXXIV',
 'MMMDCCCXC',
 'MMMCMXVI',
 'MDCLXII',
 'MCCLXXIV',
 'MCLXIV',
 'DCCCX',
 'MMMDCCCXLIV',
 'MDCXXX',
 'CMLVII',
 'MMDCCX',
 'MMDI',
 'MMMLXXIX',
 'CCCXXXIII',
 'MMDCCCXVI',
 'DII',
 'MMCLXXIV',
 'MMMCD',
 'MMDXXIII',
 'MMMXXI',
 'MDCCXCII',
 'MMCMX',
 'CMLXV',
 'XCV',
 'MDCCCXCVIII',
 'MMCDVIII',
 'MLXXIV',
 'MMCCCXXVII',
 'MMMDLVI',
 'MMDIV',
 'MMMCMXLV',
 'MMDXCVI',
 'MCLXXIX',
 'DLXXV',
 'MCCVII',
 'V',
 ...]

In [255]:
import hashlib

numeral_string = ''.join(c for c in numerals)
ascii_interp  = ''.join(str(ord(c)) for c in numeral_string)

m = hashlib.md5()
m.update(ascii_interp.encode())
result = m.hexdigest()
result[0:9]

'908ad0a4b'